# Generated by Django 4.2.6 on 2023-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='split_name',
            field=models.CharField(default='Error', max_length=20),
        ),
    ]
